@Library('javahome-demo') _

pipeline{
    agent any
    stages{
        stage('Greeting'){
            steps{
                welcome('Debi Prasad')
            }
        }
        
        stage('Calculation'){
            steps{
                script{
                    calculator.add(5,10)
                    calculator.mul(10,20)
                }
            }
        }
        
    }
}
